"""Fuzzy rule base — antecedents, consequents, rule evaluation.

A rule is `IF <var> IS <term> AND ... THEN <output> IS <term>`, held as data so
it can be saved, validated, and edited in a grid rather than generated by a
Python loop.

`Rule` is a `NamedTuple` of `(antecedents, consequent)`, which is exactly the
shape `MamdaniFIS` already iterates over, so a `RuleBase` drops straight into an
existing FIS with no change to the inference code.
"""

from __future__ import annotations

from collections.abc import Iterator, Mapping, Sequence
from dataclasses import dataclass
from typing import Any, NamedTuple


class RuleError(ValueError):
    """A rule references an unknown variable, term, or consequent."""


class Rule(NamedTuple):
    """`IF var1 IS term1 AND var2 IS term2 THEN output IS consequent`."""

    antecedents: Mapping[str, str]
    consequent: str

    def to_spec(self) -> dict[str, Any]:
        return {"if": dict(self.antecedents), "then": self.consequent}

    @classmethod
    def from_spec(cls, data: Mapping[str, Any]) -> Rule:
        try:
            return cls(
                {str(k): str(v) for k, v in data["if"].items()}, str(data["then"])
            )
        except KeyError as exc:
            raise RuleError(f"rule entry missing {exc.args[0]!r}") from None

    def describe(self, output_name: str = "output") -> str:
        """Human-readable form, for reports and editor tooltips."""
        clauses = " AND ".join(f"{v} IS {t}" for v, t in self.antecedents.items())
        return f"IF {clauses} THEN {output_name} IS {self.consequent}"


@dataclass
class RuleBase:
    """An ordered collection of rules."""

    rules: list[Rule]

    def __iter__(self) -> Iterator[Rule]:
        return iter(self.rules)

    def __len__(self) -> int:
        return len(self.rules)

    def __getitem__(self, i: int) -> Rule:
        return self.rules[i]

    def to_spec(self) -> list[dict[str, Any]]:
        return [r.to_spec() for r in self.rules]

    @classmethod
    def from_spec(cls, data: Sequence[Mapping[str, Any]]) -> RuleBase:
        return cls([Rule.from_spec(r) for r in data])

    # -- grid form, which is how two-input phase-plane controllers are authored --

    @classmethod
    def from_table(
        cls,
        row_var: str,
        col_var: str,
        row_terms: Sequence[str],
        col_terms: Sequence[str],
        table: Sequence[Sequence[str]],
    ) -> RuleBase:
        """Build the full cross-product from a `row_terms` x `col_terms` table.

        `table[i][j]` is the consequent when `row_var` is `row_terms[i]` and
        `col_var` is `col_terms[j]`.
        """
        if len(table) != len(row_terms):
            raise RuleError(
                f"table has {len(table)} rows but {len(row_terms)} row terms"
            )
        rules = []
        for i, row_term in enumerate(row_terms):
            if len(table[i]) != len(col_terms):
                raise RuleError(
                    f"table row {i} has {len(table[i])} entries but "
                    f"{len(col_terms)} column terms"
                )
            for j, col_term in enumerate(col_terms):
                rules.append(Rule({col_var: col_term, row_var: row_term}, table[i][j]))
        return cls(rules)

    def as_table(
        self,
        row_var: str,
        col_var: str,
        row_terms: Sequence[str],
        col_terms: Sequence[str],
    ) -> list[list[str | None]]:
        """Project back to a grid, for a rule-matrix editor or a heatmap.

        Cells with no matching rule are `None`, which is how an editor shows an
        incomplete rule base.
        """
        lookup = {
            (r.antecedents.get(row_var), r.antecedents.get(col_var)): r.consequent
            for r in self.rules
        }
        return [[lookup.get((rt, ct)) for ct in col_terms] for rt in row_terms]

    # -- validation --

    def validate(
        self,
        inputs: Mapping[str, Sequence[str]],
        output_terms: Sequence[str],
    ) -> list[str]:
        """Return a list of problems; empty means valid.

        Returned as data rather than raised so an editor can highlight every
        offending rule at once instead of stopping at the first.
        """
        problems: list[str] = []
        for n, rule in enumerate(self.rules):
            for var, term in rule.antecedents.items():
                if var not in inputs:
                    problems.append(f"rule {n}: unknown input variable {var!r}")
                elif term not in inputs[var]:
                    problems.append(f"rule {n}: {var!r} has no term {term!r}")
            if rule.consequent not in output_terms:
                problems.append(
                    f"rule {n}: unknown consequent term {rule.consequent!r}"
                )
        return problems

    def coverage(self, inputs: Mapping[str, Sequence[str]]) -> float:
        """Fraction of the input term cross-product covered by some rule.

        Below 1 means some input combination fires no rule at all, and the
        defuzzifier falls back to the universe midpoint for it.
        """
        total = 1
        for terms in inputs.values():
            total *= len(terms)
        if total == 0:
            return 0.0
        seen = {
            tuple(sorted(r.antecedents.items()))
            for r in self.rules
            if set(r.antecedents) == set(inputs)
        }
        return len(seen) / total
