"""SDOF active vibration control with Mamdani fuzzy logic.

PCS5708 — Exercício 2 — Controle ativo de vibrações em estrutura SDOF.

Plant
-----
Single-degree-of-freedom mass-spring-damper:

    m * x_ddot + c * x_dot + k * x = F_ext(t) + u(t)

with harmonic excitation F_ext(t) = F0 * sin(omega * t) and active control
force u(t) generated by a Mamdani FIS.

Controller
----------
- Inputs: deslocamento (m) and velocidade (m/s) of the mass.
- Output: forca de controle u (N).
- Five linguistic terms each (NG, NP, Z, PP, PG): triangular and shoulder MFs.
- 5 x 5 phase-plane rule base — control opposes motion energetically.
- min t-norm, max aggregation, centroid defuzzification.

Outputs
-------
- figures/mf_deslocamento.png      — input variable: displacement
- figures/mf_velocidade.png        — input variable: velocity
- figures/mf_forca.png             — output variable: control force
- figures/rule_base.png            — rule-base heatmap
- figures/control_surface.png      — 3D control surface u = FIS(x, x_dot)
- figures/simulation.png           — application example at resonance
- figures/frequency_response.png   — uncontrolled vs. controlled across freq
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

# Allow running from anywhere by putting the repo root on sys.path.
REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from fuzzy.fis import MamdaniFIS  # noqa: E402
from fuzzy.membership import left_shoulder, right_shoulder, triangular  # noqa: E402


# ----- Plant parameters -----------------------------------------------------

M = 1.0                                 # kg
K = 100.0                               # N/m
ZETA = 0.02                             # damping ratio
C = 2.0 * ZETA * np.sqrt(K * M)         # N·s/m
F0 = 1.0                                # N (forcing amplitude)
OMEGA_N = float(np.sqrt(K / M))         # rad/s

# Universe-of-discourse limits (selected to bracket the uncontrolled response).
X_MAX = 0.3        # m
V_MAX = 3.0        # m/s
U_MAX = 3.0        # N


# ----- Membership functions -------------------------------------------------


def _five_term_partition(low: float, high: float) -> dict:
    """Build five MFs (NG, NP, Z, PP, PG) over [low, high].

    NG and PG are linear shoulders; NP, Z, PP are triangulars centered at
    -X/2, 0, X/2. Each term overlaps its neighbors at half-membership.
    """
    quarter = 0.25 * (high - low)
    c_ng = low
    c_np = low + quarter
    c_z = 0.5 * (low + high)
    c_pp = high - quarter
    c_pg = high

    def NG(x):
        return left_shoulder(x, c_ng, c_np)

    def NP(x):
        return triangular(x, c_ng, c_np, c_z)

    def Z(x):
        return triangular(x, c_np, c_z, c_pp)

    def PP(x):
        return triangular(x, c_z, c_pp, c_pg)

    def PG(x):
        return right_shoulder(x, c_pp, c_pg)

    return {"NG": NG, "NP": NP, "Z": Z, "PP": PP, "PG": PG}


DISP_TERMS = _five_term_partition(-X_MAX, X_MAX)
VEL_TERMS = _five_term_partition(-V_MAX, V_MAX)
FORCE_TERMS = _five_term_partition(-U_MAX, U_MAX)


# ----- Rule base ------------------------------------------------------------

# Phase-plane rule base. Rows: velocidade. Columns: deslocamento.
# Read: when velocidade and deslocamento are both PG, force is NG (push back).
TERM_ORDER = ["NG", "NP", "Z", "PP", "PG"]
RULE_TABLE = [
    # x:  NG    NP    Z     PP    PG
    [    "PG", "PG", "PG", "PP", "Z"],   # v = NG
    [    "PG", "PP", "PP", "Z",  "NP"],  # v = NP
    [    "PG", "PP", "Z",  "NP", "NG"],  # v = Z
    [    "PP", "Z",  "NP", "NP", "NG"],  # v = PP
    [    "Z",  "NP", "NG", "NG", "NG"],  # v = PG
]

INPUTS = {
    "deslocamento": DISP_TERMS,
    "velocidade": VEL_TERMS,
}
OUTPUT_UNIVERSE = np.linspace(-U_MAX, U_MAX, 401)


def _build_rules() -> list:
    rules = []
    for i, vel_term in enumerate(TERM_ORDER):
        for j, disp_term in enumerate(TERM_ORDER):
            cons = RULE_TABLE[i][j]
            rules.append(
                ({"deslocamento": disp_term, "velocidade": vel_term}, cons)
            )
    return rules


def build_fis() -> MamdaniFIS:
    return MamdaniFIS(
        inputs=INPUTS,
        output_terms=FORCE_TERMS,
        output_universe=OUTPUT_UNIVERSE,
        rules=_build_rules(),
    )


# ----- Plant simulation -----------------------------------------------------


def _harmonic(t: float, omega: float) -> float:
    return F0 * np.sin(omega * t)


def _deriv(state: np.ndarray, t: float, omega: float, u: float) -> np.ndarray:
    """ODE right-hand side for SDOF: state = [x, x_dot]."""
    x, v = state
    F = _harmonic(t, omega)
    accel = (F + u - C * v - K * x) / M
    return np.array([v, accel])


def simulate(
    omega: float,
    t_max: float,
    dt: float,
    fis: MamdaniFIS | None = None,
    x0: float = 0.0,
    v0: float = 0.0,
) -> dict[str, np.ndarray]:
    """RK4 simulation with zero-order-hold on the control force.

    If `fis` is None, runs the open-loop response (u = 0).
    """
    n_steps = int(t_max / dt) + 1
    t = np.zeros(n_steps)
    x = np.zeros(n_steps)
    v = np.zeros(n_steps)
    u = np.zeros(n_steps)
    state = np.array([x0, v0])

    for i in range(n_steps - 1):
        if fis is None:
            u_now = 0.0
        else:
            xc = float(np.clip(state[0], -X_MAX, X_MAX))
            vc = float(np.clip(state[1], -V_MAX, V_MAX))
            u_now = fis.evaluate({"deslocamento": xc, "velocidade": vc})
        u[i] = u_now

        # RK4 with constant u over the step (zero-order hold).
        k1 = _deriv(state, t[i], omega, u_now)
        k2 = _deriv(state + 0.5 * dt * k1, t[i] + 0.5 * dt, omega, u_now)
        k3 = _deriv(state + 0.5 * dt * k2, t[i] + 0.5 * dt, omega, u_now)
        k4 = _deriv(state + dt * k3, t[i] + dt, omega, u_now)
        state = state + (dt / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)

        x[i + 1] = state[0]
        v[i + 1] = state[1]
        t[i + 1] = t[i] + dt

    if fis is not None:
        xc = float(np.clip(state[0], -X_MAX, X_MAX))
        vc = float(np.clip(state[1], -V_MAX, V_MAX))
        u[-1] = fis.evaluate({"deslocamento": xc, "velocidade": vc})

    return {"t": t, "x": x, "v": v, "u": u}


# ----- Plotting -------------------------------------------------------------

# Five evenly spaced colours that read in order (most-negative → most-positive).
PALETTE = ["#d62728", "#ff7f0e", "#1f77b4", "#2ca02c", "#9467bd"]


def _plot_terms(ax, terms_dict, low, high, title, xlabel, ylabel):
    x = np.linspace(low, high, 1001)
    for color, name in zip(PALETTE, TERM_ORDER):
        ax.plot(x, terms_dict[name](x), color=color, lw=2, label=name)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.set_ylim(-0.05, 1.1)
    ax.legend(loc="upper center", ncol=5, frameon=False, fontsize=9)
    ax.grid(alpha=0.3)


def plot_mf_deslocamento(figdir: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 3.5))
    _plot_terms(
        ax, DISP_TERMS, -X_MAX, X_MAX,
        "Variável de entrada: deslocamento",
        "x (m)", r"$\mu(x)$",
    )
    fig.tight_layout()
    fig.savefig(figdir / "mf_deslocamento.png", dpi=140)
    plt.close(fig)


def plot_mf_velocidade(figdir: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 3.5))
    _plot_terms(
        ax, VEL_TERMS, -V_MAX, V_MAX,
        "Variável de entrada: velocidade",
        r"$\dot x$ (m/s)", r"$\mu(\dot x)$",
    )
    fig.tight_layout()
    fig.savefig(figdir / "mf_velocidade.png", dpi=140)
    plt.close(fig)


def plot_mf_forca(figdir: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 3.5))
    _plot_terms(
        ax, FORCE_TERMS, -U_MAX, U_MAX,
        "Variável de saída: força de controle",
        "u (N)", r"$\mu(u)$",
    )
    fig.tight_layout()
    fig.savefig(figdir / "mf_forca.png", dpi=140)
    plt.close(fig)


def plot_rule_base(figdir: Path) -> None:
    score = {"NG": -2, "NP": -1, "Z": 0, "PP": 1, "PG": 2}
    matrix = np.array([[score[t] for t in row] for row in RULE_TABLE])

    fig, ax = plt.subplots(figsize=(7.0, 5.5))
    im = ax.imshow(matrix, cmap="RdYlGn", vmin=-2, vmax=2, aspect="auto")
    for i in range(5):
        for j in range(5):
            ax.text(
                j, i, RULE_TABLE[i][j],
                ha="center", va="center",
                color="black", fontsize=12, fontweight="bold",
            )

    ax.set_xticks(range(5))
    ax.set_xticklabels(TERM_ORDER)
    ax.set_yticks(range(5))
    ax.set_yticklabels(TERM_ORDER)
    ax.set_xlabel("Deslocamento (x)")
    ax.set_ylabel("Velocidade ($\\dot x$)")
    ax.set_title("Base de regras 5 × 5  →  termo de saída u")
    cbar = fig.colorbar(im, ax=ax, ticks=[-2, -1, 0, 1, 2], label="Saída u")
    cbar.set_ticklabels(TERM_ORDER)
    fig.tight_layout()
    fig.savefig(figdir / "rule_base.png", dpi=140)
    plt.close(fig)


def plot_control_surface(fis: MamdaniFIS, figdir: Path) -> None:
    xs = np.linspace(-X_MAX, X_MAX, 31)
    vs = np.linspace(-V_MAX, V_MAX, 31)
    Z = np.zeros((len(vs), len(xs)))
    for i, v in enumerate(vs):
        for j, x in enumerate(xs):
            Z[i, j] = fis.evaluate(
                {"deslocamento": float(x), "velocidade": float(v)}
            )

    fig = plt.figure(figsize=(7.5, 5.4))
    ax = fig.add_subplot(111, projection="3d")
    XX, VV = np.meshgrid(xs, vs)
    surf = ax.plot_surface(
        XX, VV, Z, cmap="RdYlGn", edgecolor="none", alpha=0.95
    )
    ax.set_xlabel("Deslocamento x (m)")
    ax.set_ylabel(r"Velocidade $\dot x$ (m/s)")
    ax.set_zlabel("Força u (N)")
    ax.set_title("Superfície de controle")
    fig.colorbar(surf, shrink=0.6, aspect=12, label="N")
    fig.tight_layout()
    fig.savefig(figdir / "control_surface.png", dpi=140)
    plt.close(fig)


def plot_simulation(fis: MamdaniFIS, figdir: Path) -> dict[str, float]:
    """Time-domain comparison at resonance (omega = omega_n).

    Returns a small dict of summary metrics for the report.
    """
    omega = OMEGA_N
    t_max = 12.0
    dt = 0.005

    h_open = simulate(omega, t_max=t_max, dt=dt, fis=None)
    h_ctrl = simulate(omega, t_max=t_max, dt=dt, fis=fis)

    fig, axes = plt.subplots(3, 1, figsize=(8.0, 7.0), sharex=True)

    axes[0].plot(h_open["t"], h_open["x"], color="#d62728", lw=1.5,
                 label="Sem controle", alpha=0.8)
    axes[0].plot(h_ctrl["t"], h_ctrl["x"], color="#1f77b4", lw=1.5,
                 label="Com controle fuzzy")
    axes[0].set_ylabel("Deslocamento x (m)")
    axes[0].legend(loc="upper right")
    axes[0].grid(alpha=0.3)

    axes[1].plot(h_open["t"], h_open["v"], color="#d62728", lw=1.5,
                 alpha=0.8)
    axes[1].plot(h_ctrl["t"], h_ctrl["v"], color="#1f77b4", lw=1.5)
    axes[1].set_ylabel(r"Velocidade $\dot x$ (m/s)")
    axes[1].grid(alpha=0.3)

    F_ext = F0 * np.sin(omega * h_ctrl["t"])
    axes[2].plot(h_ctrl["t"], F_ext, color="gray", lw=1.0,
                 label=r"$F_\mathrm{ext}(t)$", alpha=0.7)
    axes[2].plot(h_ctrl["t"], h_ctrl["u"], color="#2ca02c", lw=1.5,
                 label="u(t)  (fuzzy)")
    axes[2].set_ylabel("Força (N)")
    axes[2].set_xlabel("Tempo (s)")
    axes[2].legend(loc="upper right")
    axes[2].grid(alpha=0.3)

    fig.suptitle(
        "Exemplo de aplicação — excitação harmônica em ressonância "
        rf"($\omega = \omega_n = {OMEGA_N:.1f}$ rad/s)"
    )
    fig.tight_layout()
    fig.savefig(figdir / "simulation.png", dpi=140)
    plt.close(fig)

    # Metrics on the last 4 seconds (steady-state regime).
    last4 = h_ctrl["t"] >= (t_max - 4.0)
    peak_open = float(np.max(np.abs(h_open["x"][last4])))
    peak_ctrl = float(np.max(np.abs(h_ctrl["x"][last4])))
    rms_open = float(np.sqrt(np.mean(h_open["x"][last4] ** 2)))
    rms_ctrl = float(np.sqrt(np.mean(h_ctrl["x"][last4] ** 2)))
    return {
        "peak_open": peak_open,
        "peak_ctrl": peak_ctrl,
        "rms_open": rms_open,
        "rms_ctrl": rms_ctrl,
        "u_peak": float(np.max(np.abs(h_ctrl["u"]))),
    }


def plot_frequency_response(fis: MamdaniFIS, figdir: Path) -> None:
    """Steady-state amplitude over a frequency sweep, controlled vs. open."""
    omegas = np.linspace(0.4 * OMEGA_N, 1.8 * OMEGA_N, 18)
    t_max = 18.0
    dt = 0.005

    amp_open = np.zeros_like(omegas)
    amp_ctrl = np.zeros_like(omegas)

    for i, om in enumerate(omegas):
        h_o = simulate(om, t_max=t_max, dt=dt, fis=None)
        h_c = simulate(om, t_max=t_max, dt=dt, fis=fis)
        last = h_o["t"] >= (t_max - 4.0)
        amp_open[i] = np.max(np.abs(h_o["x"][last]))
        amp_ctrl[i] = np.max(np.abs(h_c["x"][last]))

    fig, ax = plt.subplots(figsize=(7.5, 4.6))
    ax.plot(omegas / OMEGA_N, amp_open, color="#d62728", marker="o",
            lw=1.8, markersize=5, label="Sem controle")
    ax.plot(omegas / OMEGA_N, amp_ctrl, color="#1f77b4", marker="o",
            lw=1.8, markersize=5, label="Com controle fuzzy")
    ax.axvline(1.0, color="gray", linestyle=":", alpha=0.6,
               label=r"$\omega_n$")
    ax.set_xlabel(r"$\omega / \omega_n$")
    ax.set_ylabel("Amplitude de regime (m)")
    ax.set_title("Resposta em frequência")
    ax.legend()
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(figdir / "frequency_response.png", dpi=140)
    plt.close(fig)


# ----- Entry point ----------------------------------------------------------


def main() -> None:
    np.random.seed(0)
    fis = build_fis()

    here = Path(__file__).parent
    figdir = here / "figures"
    figdir.mkdir(parents=True, exist_ok=True)

    plot_mf_deslocamento(figdir)
    plot_mf_velocidade(figdir)
    plot_mf_forca(figdir)
    plot_rule_base(figdir)
    plot_control_surface(fis, figdir)
    metrics = plot_simulation(fis, figdir)
    plot_frequency_response(fis, figdir)

    print("Plant: m=1 kg, k=100 N/m, zeta=0.02 → omega_n=10 rad/s")
    print(f"Forcing: F0={F0} N at omega = omega_n (resonance)")
    print()
    print("Steady-state response (last 4 s):")
    print(f"  peak |x|     uncontrolled = {metrics['peak_open']:.4f} m")
    print(f"  peak |x|     controlled   = {metrics['peak_ctrl']:.4f} m"
          f"  ({100 * (1 - metrics['peak_ctrl']/metrics['peak_open']):.1f}% reduction)")
    print(f"  rms  x       uncontrolled = {metrics['rms_open']:.4f} m")
    print(f"  rms  x       controlled   = {metrics['rms_ctrl']:.4f} m"
          f"  ({100 * (1 - metrics['rms_ctrl']/metrics['rms_open']):.1f}% reduction)")
    print(f"  peak |u|                  = {metrics['u_peak']:.4f} N")
    print()
    print(f"Figures saved to: {figdir}")


if __name__ == "__main__":
    main()
