"""SDOF active vibration control with Mamdani fuzzy logic.

PCS5708 — Exercício 2 — Controle ativo de vibrações em estrutura SDOF.

Plant
-----
Single-degree-of-freedom mass-spring-damper:

    m * x_ddot + c * x_dot + k * x = F_ext(t) + u(t)

with harmonic excitation F_ext(t) = F0 * sin(omega * t) and active control
force u(t) generated by a Mamdani FIS.

Controller
----------
- Inputs: deslocamento (m) and velocidade (m/s) of the mass.
- Output: forca de controle u (N).
- Five linguistic terms each (NG, NP, Z, PP, PG): triangular and shoulder MFs.
- 5 x 5 phase-plane rule base — control opposes motion energetically.
- min t-norm, max aggregation, centroid defuzzification.

Simulation
----------
The plant, excitation, actuator, and controller are assembled as a block
diagram (`fuzzy.sim`) rather than a hand-rolled integration loop, so the same
diagram serves the open-loop, fuzzy, and PID cases and can be saved as a spec
file for the graphical editor. See `docs/design-block-diagram-simulation.md`.

Metric horizon
--------------
`T_MAX = 40 s`. The plant's transient decays with `tau = 1/(zeta*omega_n) = 5 s`,
so the earlier 12 s horizon left the *uncontrolled* reference 9 % below its true
amplitude while the controlled cases had already settled — a one-sided bias in
every reported reduction. `fuzzy.metrics.steady_state` now warns when the window
is not genuinely steady state.

Outputs
-------
- figures/mf_deslocamento.png      — input variable: displacement
- figures/mf_velocidade.png        — input variable: velocity
- figures/mf_forca.png             — output variable: control force
- figures/rule_base.png            — rule-base heatmap
- figures/control_surface.png      — 3D control surface u = FIS(x, x_dot)
- figures/simulation.png           — application example at resonance
- figures/frequency_response.png   — uncontrolled vs. controlled across freq
- diagram.json                     — block-diagram spec (editor fixture)
- diagram.mmd                      — Mermaid block diagram, embedded in REPORT.md
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from fuzzy.blocks import (
    Block,
    Constant,
    FISBlock,
    Harmonic,
    Saturation,
    Select,
    Sum,
    sdof_plant,
)
from fuzzy.fis import FISSpec, MamdaniFIS
from fuzzy.membership import Variable
from fuzzy.metrics import steady_state
from fuzzy.rules import RuleBase
from fuzzy.sim import Diagram, Log, simulate
from fuzzy.spec import save

# ----- Plant parameters -----------------------------------------------------

M = 1.0                                 # kg
K = 100.0                               # N/m
ZETA = 0.02                             # damping ratio
C = 2.0 * ZETA * np.sqrt(K * M)         # N·s/m
F0 = 1.0                                # N (forcing amplitude)
OMEGA_N = float(np.sqrt(K / M))         # rad/s

# Universe-of-discourse limits (selected to bracket the uncontrolled response).
X_MAX = 0.3        # m
V_MAX = 3.0        # m/s
U_MAX = 3.0        # N

# ----- Simulation settings --------------------------------------------------

DT = 0.005                  # s — control period and integration step
T_MAX = 40.0                # s — >= 4*tau settling (20 s) plus the metric window
METRIC_WINDOW = 4.0         # s — trailing window used for steady-state metrics
TAU = 1.0 / (ZETA * OMEGA_N)  # s — open-loop transient decay time constant


# ----- Linguistic variables -------------------------------------------------

# `Variable.partition` builds the standard strong partition: linear shoulders at
# the ends, triangles between, centres evenly spaced, neighbours meeting at
# half-membership so memberships sum to exactly 1 everywhere. Terms are data, not
# closures, so the controller can be saved, validated, and edited.
TERM_ORDER = ["NG", "NP", "Z", "PP", "PG"]

DISP = Variable.partition("deslocamento", -X_MAX, X_MAX, TERM_ORDER)
VEL = Variable.partition("velocidade", -V_MAX, V_MAX, TERM_ORDER)
FORCE = Variable.partition("forca", -U_MAX, U_MAX, TERM_ORDER)


# ----- Rule base ------------------------------------------------------------

# Phase-plane rule base. Rows: velocidade. Columns: deslocamento.
# Read: when velocidade and deslocamento are both PG, force is NG (push back).
RULE_TABLE = [
    # x:  NG    NP    Z     PP    PG
    [    "PG", "PG", "PG", "PP", "Z"],   # v = NG
    [    "PG", "PP", "PP", "Z",  "NP"],  # v = NP
    [    "PG", "PP", "Z",  "NP", "NG"],  # v = Z
    [    "PP", "Z",  "NP", "NP", "NG"],  # v = PP
    [    "Z",  "NP", "NG", "NG", "NG"],  # v = PG
]

RULES = RuleBase.from_table(
    row_var="velocidade",
    col_var="deslocamento",
    row_terms=TERM_ORDER,
    col_terms=TERM_ORDER,
    table=RULE_TABLE,
)

OUTPUT_RESOLUTION = 401


def build_fis_spec() -> FISSpec:
    """The controller as data — serialisable, validatable, editable."""
    return FISSpec(
        inputs={"deslocamento": DISP, "velocidade": VEL},
        output=FORCE,
        rules=RULES,
        resolution=OUTPUT_RESOLUTION,
    )


def build_fis() -> MamdaniFIS:
    """The runnable inference system built from the spec."""
    return build_fis_spec().build()


# ----- Block diagram --------------------------------------------------------

FUZZY_PORTS = ("deslocamento", "velocidade")
"""Displacement and velocity input ports of the fuzzy controller."""

_LAYOUT = {
    "force": {"x": 40.0, "y": 40.0},
    "total": {"x": 200.0, "y": 120.0},
    "plant": {"x": 360.0, "y": 120.0},
    "pos": {"x": 520.0, "y": 40.0},
    "vel": {"x": 520.0, "y": 200.0},
    "controller": {"x": 680.0, "y": 120.0},
    "actuator": {"x": 680.0, "y": 260.0},
}


def fuzzy_controller(gain: float = 1.0, name: str = "controller") -> FISBlock:
    """The Mamdani controller as a sampled block.

    `gain` scales both inputs before they reach the FIS: `gain=10` is equivalent
    to a 10x tighter universe of discourse, and is the fuzzy analogue of raising
    a state-feedback gain vector `K`.
    """
    return FISBlock(
        build_fis_spec(),
        gain={port: gain for port in FUZZY_PORTS},
        clip={FUZZY_PORTS[0]: (-X_MAX, X_MAX), FUZZY_PORTS[1]: (-V_MAX, V_MAX)},
        name=name,
    )


def build_diagram(
    controller: Block | None = None,
    ports: tuple[str, str] = FUZZY_PORTS,
    omega: float = OMEGA_N,
    x0: float = 0.0,
    v0: float = 0.0,
    name: str = "sdof",
) -> Diagram:
    """Assemble the SDOF plant with harmonic forcing and an optional controller.

    `controller is None` gives the open-loop response. `ports` names the
    controller's displacement and velocity inputs, in that order.
    """
    d = Diagram(name=name)
    plant = sdof_plant(M, C, K, x0=x0, v0=v0, name="plant")
    force = Harmonic(amplitude=F0, omega=omega, name="force")
    total = Sum(("ext", "ctrl"), name="total")

    d.connect(force, (total, "ext"))
    d.connect(total, plant)

    if controller is None:
        d.connect(Constant(0.0, name="controller"), (total, "ctrl"))
    else:
        # The actuator limit is stated once and shared by every controller, so
        # the comparison cannot drift into unequal authority.
        actuator = Saturation(-U_MAX, U_MAX, name="actuator")
        pos, vel = Select(0, name="pos"), Select(1, name="vel")
        d.connect(plant, pos)
        d.connect(plant, vel)
        d.connect(pos, (controller, ports[0]))
        d.connect(vel, (controller, ports[1]))
        d.connect(controller, actuator)
        d.connect(actuator, (total, "ctrl"))

    present = {b.name for b in d.blocks}
    d.layout.update({k: v for k, v in _LAYOUT.items() if k in present})
    return d


def run(
    controller: Block | None = None,
    ports: tuple[str, str] = FUZZY_PORTS,
    omega: float = OMEGA_N,
    t_max: float = T_MAX,
) -> Log:
    """Build and simulate in one step."""
    d = build_diagram(controller, ports=ports, omega=omega)
    return simulate(d, t_max=t_max, dt_control=DT)


def response_metrics(log: Log) -> dict[str, float]:
    """Steady-state displacement and control-effort metrics for one run.

    Every entry uses the same trailing window — the earlier `u_peak` was a
    whole-run maximum reported inside a steady-state table.
    """
    x = steady_state(log, "plant.y", window=METRIC_WINDOW, index=0, tau=TAU)
    out = {"peak": x["peak"], "rms": x["rms"]}
    if "actuator.y" in log.signals:
        out["u_peak"] = steady_state(log, "actuator.y", window=METRIC_WINDOW)["peak"]
    return out


# ----- Plotting -------------------------------------------------------------

# Five evenly spaced colours that read in order (most-negative → most-positive).
PALETTE = ["#d62728", "#ff7f0e", "#1f77b4", "#2ca02c", "#9467bd"]


def _plot_terms(ax, terms_dict, low, high, title, xlabel, ylabel):
    x = np.linspace(low, high, 1001)
    for color, name in zip(PALETTE, TERM_ORDER, strict=True):
        ax.plot(x, terms_dict[name](x), color=color, lw=2, label=name)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.set_ylim(-0.05, 1.1)
    ax.legend(loc="upper center", ncol=5, frameon=False, fontsize=9)
    ax.grid(alpha=0.3)


def plot_mf_deslocamento(figdir: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 3.5))
    _plot_terms(
        ax, DISP.terms, -X_MAX, X_MAX,
        "Variável de entrada: deslocamento",
        "x (m)", r"$\mu(x)$",
    )
    fig.tight_layout()
    fig.savefig(figdir / "mf_deslocamento.png", dpi=140)
    plt.close(fig)


def plot_mf_velocidade(figdir: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 3.5))
    _plot_terms(
        ax, VEL.terms, -V_MAX, V_MAX,
        "Variável de entrada: velocidade",
        r"$\dot x$ (m/s)", r"$\mu(\dot x)$",
    )
    fig.tight_layout()
    fig.savefig(figdir / "mf_velocidade.png", dpi=140)
    plt.close(fig)


def plot_mf_forca(figdir: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 3.5))
    _plot_terms(
        ax, FORCE.terms, -U_MAX, U_MAX,
        "Variável de saída: força de controle",
        "u (N)", r"$\mu(u)$",
    )
    fig.tight_layout()
    fig.savefig(figdir / "mf_forca.png", dpi=140)
    plt.close(fig)


def plot_rule_base(figdir: Path) -> None:
    score = {"NG": -2, "NP": -1, "Z": 0, "PP": 1, "PG": 2}
    # Projected back out of the rule base itself, so the figure cannot drift
    # from the rules that actually ran.
    table = RULES.as_table("velocidade", "deslocamento", TERM_ORDER, TERM_ORDER)
    matrix = np.array([[score[t] for t in row] for row in table])

    fig, ax = plt.subplots(figsize=(7.0, 5.5))
    im = ax.imshow(matrix, cmap="RdYlGn", vmin=-2, vmax=2, aspect="auto")
    for i in range(5):
        for j in range(5):
            ax.text(
                j, i, table[i][j],
                ha="center", va="center",
                color="black", fontsize=12, fontweight="bold",
            )

    ax.set_xticks(range(5))
    ax.set_xticklabels(TERM_ORDER)
    ax.set_yticks(range(5))
    ax.set_yticklabels(TERM_ORDER)
    ax.set_xlabel("Deslocamento (x)")
    ax.set_ylabel("Velocidade ($\\dot x$)")
    ax.set_title("Base de regras 5 × 5  →  termo de saída u")
    cbar = fig.colorbar(im, ax=ax, ticks=[-2, -1, 0, 1, 2], label="Saída u")
    cbar.set_ticklabels(TERM_ORDER)
    fig.tight_layout()
    fig.savefig(figdir / "rule_base.png", dpi=140)
    plt.close(fig)


def plot_control_surface(fis: MamdaniFIS, figdir: Path) -> None:
    xs = np.linspace(-X_MAX, X_MAX, 31)
    vs = np.linspace(-V_MAX, V_MAX, 31)
    Z = np.zeros((len(vs), len(xs)))
    for i, v in enumerate(vs):
        for j, x in enumerate(xs):
            Z[i, j] = fis.evaluate(
                {"deslocamento": float(x), "velocidade": float(v)}
            )

    fig = plt.figure(figsize=(7.5, 5.4))
    ax = fig.add_subplot(111, projection="3d")
    XX, VV = np.meshgrid(xs, vs)
    surf = ax.plot_surface(
        XX, VV, Z, cmap="RdYlGn", edgecolor="none", alpha=0.95
    )
    ax.set_xlabel("Deslocamento x (m)")
    ax.set_ylabel(r"Velocidade $\dot x$ (m/s)")
    ax.set_zlabel("Força u (N)")
    ax.set_title("Superfície de controle")
    fig.colorbar(surf, shrink=0.6, aspect=12, label="N")
    fig.tight_layout()
    fig.savefig(figdir / "control_surface.png", dpi=140)
    plt.close(fig)


def plot_simulation(figdir: Path) -> dict[str, dict[str, float]]:
    """Time-domain comparison at resonance (omega = omega_n).

    The full 40 s horizon is plotted, so the uncontrolled envelope is visibly
    still growing toward its analytic asymptote F0/(c*omega_n) = 0.25 m.
    """
    open_log = run(None)
    ctrl_log = run(fuzzy_controller())

    fig, axes = plt.subplots(3, 1, figsize=(10.0, 7.4), sharex=True)

    axes[0].plot(open_log.t, open_log.col("plant.y", 0), color="#d62728", lw=1.0,
                 label="Sem controle", alpha=0.8)
    axes[0].plot(ctrl_log.t, ctrl_log.col("plant.y", 0), color="#1f77b4", lw=1.0,
                 label="Com controle fuzzy")
    axes[0].axhline(F0 / (C * OMEGA_N), color="gray", linestyle=":", alpha=0.7,
                    label=r"$F_0/(c\,\omega_n)$")
    axes[0].axhline(-F0 / (C * OMEGA_N), color="gray", linestyle=":", alpha=0.7)
    axes[0].set_ylabel("Deslocamento x (m)")
    axes[0].legend(loc="upper right", ncol=3, fontsize=9)
    axes[0].grid(alpha=0.3)

    axes[1].plot(open_log.t, open_log.col("plant.y", 1), color="#d62728", lw=1.0,
                 alpha=0.8)
    axes[1].plot(ctrl_log.t, ctrl_log.col("plant.y", 1), color="#1f77b4", lw=1.0)
    axes[1].set_ylabel(r"Velocidade $\dot x$ (m/s)")
    axes[1].grid(alpha=0.3)

    axes[2].plot(ctrl_log.t, ctrl_log["force.y"], color="gray", lw=0.8,
                 label=r"$F_\mathrm{ext}(t)$", alpha=0.6)
    axes[2].plot(ctrl_log.t, ctrl_log["actuator.y"], color="#2ca02c", lw=1.0,
                 label="u(t)  (fuzzy)")
    axes[2].set_ylabel("Força (N)")
    axes[2].set_xlabel("Tempo (s)")
    axes[2].axvspan(T_MAX - METRIC_WINDOW, T_MAX, color="black", alpha=0.06,
                    label="janela de regime")
    axes[2].legend(loc="upper right", ncol=3, fontsize=9)
    axes[2].grid(alpha=0.3)

    fig.suptitle(
        "Exemplo de aplicação — excitação harmônica em ressonância "
        rf"($\omega = \omega_n = {OMEGA_N:.1f}$ rad/s)"
    )
    fig.tight_layout()
    fig.savefig(figdir / "simulation.png", dpi=140)
    plt.close(fig)

    return {"open": response_metrics(open_log), "fuzzy": response_metrics(ctrl_log)}


def plot_frequency_response(figdir: Path) -> None:
    """Steady-state amplitude over a frequency sweep, controlled vs. open."""
    omegas = np.linspace(0.4 * OMEGA_N, 1.8 * OMEGA_N, 18)
    amp_open = np.zeros_like(omegas)
    amp_ctrl = np.zeros_like(omegas)

    for i, om in enumerate(omegas):
        amp_open[i] = response_metrics(run(None, omega=om))["peak"]
        amp_ctrl[i] = response_metrics(run(fuzzy_controller(), omega=om))["peak"]

    fig, ax = plt.subplots(figsize=(7.5, 4.6))
    ax.plot(omegas / OMEGA_N, amp_open, color="#d62728", marker="o",
            lw=1.8, markersize=5, label="Sem controle")
    ax.plot(omegas / OMEGA_N, amp_ctrl, color="#1f77b4", marker="o",
            lw=1.8, markersize=5, label="Com controle fuzzy")
    ax.axvline(1.0, color="gray", linestyle=":", alpha=0.6,
               label=r"$\omega_n$")
    ax.set_xlabel(r"$\omega / \omega_n$")
    ax.set_ylabel("Amplitude de regime (m)")
    ax.set_title("Resposta em frequência")
    ax.legend()
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(figdir / "frequency_response.png", dpi=140)
    plt.close(fig)


# ----- Entry point ----------------------------------------------------------


def main() -> None:
    fis = build_fis()
    here = Path(__file__).parent
    figdir = here / "figures"
    figdir.mkdir(parents=True, exist_ok=True)

    plot_mf_deslocamento(figdir)
    plot_mf_velocidade(figdir)
    plot_mf_forca(figdir)
    plot_rule_base(figdir)
    plot_control_surface(fis, figdir)
    metrics = plot_simulation(figdir)
    plot_frequency_response(figdir)

    # The diagram doubles as a fixture for the block editor. The FIS itself is
    # still a live object (its terms are closures), so it round-trips as a
    # `$provide` placeholder until membership functions become declarative.
    diagram = build_diagram(fuzzy_controller(), name="ex2_sdof_fuzzy")
    spec_path = save(diagram, here / "diagram.json")
    mmd_path = here / "diagram.mmd"
    mmd_path.write_text(diagram.to_mermaid() + "\n")

    o, f = metrics["open"], metrics["fuzzy"]
    print(f"Plant: m={M:g} kg, k={K:g} N/m, zeta={ZETA} → omega_n={OMEGA_N:g} rad/s")
    print(f"Forcing: F0={F0:g} N at omega = omega_n (resonance)")
    print(f"Horizon: t_max={T_MAX:g} s (tau={TAU:g} s), "
          f"metrics over the last {METRIC_WINDOW:g} s")
    print()
    print(f"Steady-state response (last {METRIC_WINDOW:g} s):")
    print(f"  peak |x|     uncontrolled = {o['peak']:.4f} m"
          f"   (analytic F0/(c·omega_n) = {F0 / (C * OMEGA_N):.4f} m)")
    print(f"  peak |x|     controlled   = {f['peak']:.4f} m"
          f"  ({100 * (1 - f['peak'] / o['peak']):.1f}% reduction)")
    print(f"  rms  x       uncontrolled = {o['rms']:.4f} m")
    print(f"  rms  x       controlled   = {f['rms']:.4f} m"
          f"  ({100 * (1 - f['rms'] / o['rms']):.1f}% reduction)")
    print(f"  peak |u|                  = {f['u_peak']:.4f} N"
          f"   (actuator limit {U_MAX:g} N)")
    print()
    print(f"Figures saved to: {figdir}")
    print(f"Diagram spec saved to: {spec_path}")
    print(f"Block diagram saved to: {mmd_path}")


if __name__ == "__main__":
    main()
